name = "Performant Pack"
author = "ssamjh"
version = "1.18.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9c484ffa462b196c215c0d4b26355e3073d07bfc056bf39aa7280ebdf93557a"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
