name = "Performant Pack"
author = "ssamjh"
version = "1.18.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "768a4dca3031c7751190005ed12c119d8cc8cbccc689e2e396ae61e595ac6acb"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
