name = "Performant Pack"
author = "ssamjh"
version = "1.18.x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f625a89cb4ca1b2f7b1f23542f3d8c87de2977c900019dcdc5f3aecf1256d7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
